--[[
    _               _                      _____ _  ___  ____  
   / \   _ __   ___| |_ __ _ _ __ _   _ __|___  / |/ _ \| ___| 
  / _ \ | '_ \ / __| __/ _` | '__| | | / __| / /| | | | |___ \ 
 / ___ \| | | | (__| || (_| | |  | |_| \__ \/ / | | |_| |___) |
/_/   \_\_| |_|\___|\__\__,_|_|   \__,_|___/_/  |_|\___/|____/ 

]]--

function GitAud(v2,v3) SoundName=tostring(SoundName);local v4=v2;local v5=v3;writefile(v5   .. ".mp3" ,game:HttpGet(v4));return (getcustomasset or getsynasset)(v5   .. ".mp3" );end function CustomGitSound(v6,v7,v8) local v9=Instance.new("Sound");v9.SoundId=GitAud(v6,v8);v9.Parent=workspace;v9.Name="frostbitespawn";v9.Volume=23 -13 ;v9.PlaybackSpeed=928 -(214 + 713) ;v9:Play();end CustomGitSound("https://github.com/Kotyara19k-Doorsspawner/Random-files/raw/main/FrostBiteHasSpawnedAndFrozenTheRoom.mp3",1,"frostbitespawn");wait(189 -(67 + 113) );local v0=loadstring(game:HttpGet("https://raw.githubusercontent.com/RegularVynixu/Utilities/main/Doors/Entity%20Spawner/V2/Source.lua"))();local v1=v0.Create({Entity={Name="FrostBite",Asset="rbxassetid://12272255258",HeightOffset=0 + 0 },Lights={Flicker={Enabled=false,Duration=1},Shatter=true,Repair=false},Earthquake={Enabled=false},CameraShake={Enabled=true,Range=25,Values={1.5 + 0 ,897 -(282 + 595) ,0.1 + 0 ,1 -0 }},Movement={Speed=1065 -(68 + 997) ,Delay=1270 -(226 + 1044) ,Reversed=false},Rebounding={Enabled=false,Type="Ambush",Min=4 -3 ,Max=118 -(32 + 85) ,Delay=2 + 0 },Damage={Enabled=false,Range=9 + 31 ,Amount=353 -228 },Crucifixion={Enabled=true,Range=24 + 16 ,Resist=false,Break=true},Death={Type="Guiding",Hints={"You died to who you call FrostBite...","He spawn in middle and start freezing the room.","Find something that has heat to keep you warm!"},Cause="FrostBite"}});v1:SetCallback("OnSpawned",function() local v15=0 -0 ;local v16;while true do if (v15==(1187 -(1069 + 118))) then v16=depthsTer:FindFirstChildWhichIsA("BasePart") or depthsTer:FindFirstChildWhichIsA("Part") ;v16.CFrame=game.Workspace.CurrentRooms:GetChildren()[ #game.Workspace.CurrentRooms:GetChildren() -(1 -0) ].Parts.Floor.CFrame + Vector3.new(0 -0 ,2 + 4 ,350 -(87 + 263) ) ;break;end end end);v1:SetCallback("OnStartMoving",function() print("Entity has started moving");end);v1:SetCallback("OnEnterRoom",function(v17,v18) if (v18==true) then print("Entity has entered room: "   .. v17.Name   .. " for the first time" );else print("Entity has entered room: "   .. v17.Name   .. " again" );end end);v1:SetCallback("OnLookAt",function(v19) if (v19==true) then print("Player is looking at entity");else print("Player view is obstructed by something");end end);v1:SetCallback("OnRebounding",function(v20) if (v20==true) then print("Entity has started rebounding");else print("Entity has finished rebounding");end end);v1:SetCallback("OnDespawning",function() print("Entity is despawning");end);v1:SetCallback("OnDespawned",function() print("Entity has despawned");end);v1:SetCallback("OnDamagePlayer",function(v21) if (v21==(0 + 0)) then print("Entity has killed the player");else print("Entity has damaged the player");end end);v1:Run();
